<?php
echo nl2br ("NAME: BASIL JOHN SAMUEL \n EMAIL: basilsamuel76@gmail.com \r\n MATRICULATION NUMBER UG17/MDHA/1014 \r\n PROGRAMMING LANGUAGE: PHP \r\n SUB-SPECIALITY: NEUROINFOMATICS \r\n SLACK USERNAME: @BASIL SAMUEL JOHN");
?>